### ISSUE TITLE
PHP - PGSQL extension Error

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/moodle_ynh#10]
Hi
Yesterday i installed moodle - and it was working just fine
today I get:

Error: database driver problem detected
The site administrator should verify server configuration
PHP has not been properly configured with the PGSQL extension so that it can communicate with PostgreSQL. Please check your php.ini file or recompile PHP.

can someone help - that do I have to do ? 
THANKS

**Comment by rocky-III** [comment]
I get this when I install the app:
"Packagers ! Please do not use a separate php ini file, merge your directives in the pool file instead."
what does thsi mean?

**Comment by rocky-III** [comment]
after reinstall moodle was running find for tow days but now I have this error again:

Error: database driver problem detected
The site administrator should verify server configuration
PHP has not been properly configured with the PGSQL extension so that it can communicate with PostgreSQL. Please check your php.ini file or recompile PHP.

don´t know what to do... 
need help badly... please...

**Comment by rocky-III** [comment]
here are the PostgreSQL settings in the php.ini file:

[PostgreSQL]
; Allow or prevent persistent links.
; http://php.net/pgsql.allow-persistent
pgsql.allow_persistent = On

; Detect broken persistent links always with pg_pconnect().
; Auto reset feature requires a little overheads.
; http://php.net/pgsql.auto-reset-persistent
pgsql.auto_reset_persistent = Off

; Maximum number of persistent links.  -1 means no limit.
; http://php.net/pgsql.max-persistent
pgsql.max_persistent = -1

; Maximum number of links (persistent+non persistent).  -1 means no limit.
; http://php.net/pgsql.max-links
pgsql.max_links = -1

; Ignore PostgreSQL backends Notice message or not.
; Notice message logging require a little overheads.
; http://php.net/pgsql.ignore-notice
pgsql.ignore_notice = 0

; Log PostgreSQL backends Notice message or not.
; Unless pgsql.ignore_notice=0, module cannot log notice message.
; http://php.net/pgsql.log-notice
pgsql.log_notice = 0

does this look good or can I try something els?

**Comment by kay0u** [comment]
Hi,

I'm working on this package right now, I'll probably won't have time to maintain it, but I'll bring it to the highest level I can.
You can follow/test my work here:
https://github.com/YunoHost-Apps/moodle_ynh/pull/11

For now I can install and remove the app without any problem, but please, don't try to upgrade/backup/restore for now :-)

**Comment by kay0u** [comment]
Done, can you retry please?

**Comment by rocky-III** [comment]
Hi and Thanks so much for your work... right now i can´t do the reinstall... will do it tomorow... . thanks... i rally love yunohost community

**Comment by rocky-III** [comment]
just did the reinstall and it just went fine - like cream...  let´s see how stable it will run... thanks so fare

**Comment by kay0u** [comment]
Thank you for the feedback! Fingers crossed for the stability \o/

**Comment by rocky-III** [comment]
under 
> Site administration > Notifications

I see this:

"The cli/cron.php maintenance script has not been run for at least 24 hours. "

Do I have to set up the cron job manually or is something not working ?

**Comment by kay0u** [comment]
No, there is a bug with my cron job, I'll fix it!

Thanks for pointing this out!

**Comment by kay0u** [comment]
This issue should be fixed. Feel free to reopen it!
