### ISSUE TITLE
Hard-code references to postgresql-9.4 might break compatibility with Stretch

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/moodle_ynh#2]
Hellow,

I see that there are some hard-coded reference to postgresql 9.4 in the code of this package : 

e.g. : 
https://github.com/YunoHost-Apps/moodle_ynh/blob/master/scripts/_common.sh#L24

Since Stretch now has postgresql 9.6, this might break the installation or other functionalities of this app on Stretch / Yunohost 3.x

**Comment by anmol26s** [comment]
This have been fixed in the latest commit.
Thanks for pointing it out.
