### ISSUE TITLE
Minor version - request for info or addition

### ISSUE THREAD

**Issue by verzog** [YunoHost-Apps/moodle_ynh#29]
Not a bug a request.
Big fan, love ya work but was wondering about the minor versions. As a longtime Moodle user the first versions are usually never implemented and we wait till at least the 3rd minor version (eg. 3.9.3) to let the biggest of the security fixes or bugs be resolved.

How can I modify this to update with the minor versions?

Just the app.src details? (I'm more front end so this is a stretch for me).

TIA,
V

**Comment by kay0u** [comment]
Hi!

For now the latest version is the current one (3.10.0), If you want to help us when a new version is out, you can open a new PR where you update the file `app.src` witht the right `SOURCE_URL` and update the `SOURCE_SUM` as well. But it's not enough, you must edit the version in [this file](https://github.com/YunoHost-Apps/moodle_ynh/blob/946f233c6feef4a28b044ddcc56a7b5c6154a59c/manifest.json#L9) and [this one](https://github.com/YunoHost-Apps/moodle_ynh/blob/master/README.md) (Shipped version)

Does it answer your interrogations?

**Comment by verzog** [comment]
Hi Kay0u,
Thank you for this. I'll keep an eye out for 3.10.1 and see what I can do.
Much obliged,
V
