### ISSUE TITLE
Unable to install moodle in Debian 9 Stretch based yunohost

### ISSUE THREAD

**Issue by ramakirankumar** [YunoHost-Apps/moodle_ynh#3]
Hi,

Tried to install moodle in a fresh installed yunohost but it fails. Below is the error log message.

The user moodle was not found
/home/yunohost.app/moodle wasn't deleted because it doesn't exist.
/etc/cron.d/moodle wasn't deleted because it doesn't exist.
Failed to reload php7.1-fpm.service: Unit php7.1-fpm.service not found.
/etc/php/7.1/fpm/pool.d/moodle.conf wasn't deleted because it doesn't exist.
/etc/nginx/conf.d/lmsapp1.talentio.in.d/moodle.conf wasn't deleted because it doesn't exist.
Avoid deleting .
sudo: unable to initialize policy plugin
sudo: unknown user: postgres
No passwd entry for user 'postgres'
E: Unable to locate package moodle-ynh-deps
!!
moodle's script has encountered an error. Its execution was cancelled.
!!
Unable to install dependencies
E: Packages need to be removed but remove is disabled.
dpkg-preconfigure: unable to re-open stdin:
debconf: falling back to frontend: Teletype
debconf: (This frontend requires a controlling tty.)
debconf: unable to initialize frontend: Readline
debconf: falling back to frontend: Readline
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: unable to initialize frontend: Dialog

I believe the main issue is because of "E: Unable to locate package moodle-ynh-deps"
Can you let me know how to overcome this issue?

Thanks and Regards,
KiranKumar.

**Comment by anmol26s** [comment]
Hi Kiran
Sorry for late reply. The app needs to be made compatible with YunoHost 3 (Debian 9). I will try to fix it on this weekend.

Thanks

**Comment by anmol26s** [comment]
Hi 
I can install the app on Yunohost 3. Can you show complete log please? The log you gave is not indicating the exact error. The error would have occurred in the upper part of the log.

**Comment by anmol26s** [comment]
I think your problem is related to postgres.

Can you do?

`$ pg_createcluster 9.6 main --start
`
then:

`$ /etc/init.d/postgresql start
`
and show me the output?

**Comment by ramakirankumar** [comment]
Yeah, i copied the yunohost moodle app as another app and then changed the script in _common.sh under ynh_install_php7 function in line 24 - changed the word postgresql-9.4 to postgresql-9.6 and similarly in next function at line no: 32 and then installation was successful.

**Comment by ramakirankumar** [comment]
Regarding the files to take backup from moodle, the main file would be config.php that should be available in the moodle folder - this contains the whole configuration details of moodle and its database details.
The other files (optional) would be the files present inside respective themes folder unless the developer or the user did some customizations.
Thank you very much for your kind support.

**Comment by ramakirankumar** [comment]
yes, the custom data related to some look and feel changes and some files will be stored in themes folder and also in the database directly. Hence a perfect backup would be the database backup along with themes folder can ensure the user to restore the moodle back in case of any issue.
