### ISSUE TITLE
Change Postgres to MariaDB

### ISSUE THREAD

**Issue by liberodark** [YunoHost-Apps/moodle_ynh#7]
That is better for elevate version.

**Comment by rocky-III** [comment]
can you explain how i can Do this - Thanks

**Comment by rocky-III** [comment]
So you are saying that with Postgres yunhost moodle is not running stable?

How can i use the MariaDb during the installation ?

**Comment by kay0u** [comment]
It looks like it's not really necessary, everything is stable with PostgreSQL
